apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-httpbin-haiku
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: go-httpbin-haiku
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-httpbin-haiku
    spec:
      containers:
        - name: httpbin
          image: go-httpbin-haiku:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status/200
              port: http
          readinessProbe:
            httpGet:
              path: /status/200
              port: http
          resources: {}
